tauon.py

Displays artist in album artist column if album artist tag is empty.

displays artist if album artist is missing

---

.gitignore
snapcraft.yaml

Add snapcraft recipe

---

locale/fr_FR/LC_MESSAGES/tauon.po
locale/fr_FR/tauon.po

[WIP] french i18n

---

locale/sv/LC_MESSAGES/tauon.po

Hi,
Please add Swedish translation. I like this music player, would be nice to use it in my native language.

Swedish translation

---

locale/pt_PT/LC_MESSAGES/tauon.po

Complete 100% Portuguese European pt-PT (Portugal) translation for v5.4.2

Portuguese European pt-PT translation complete

---

tauon.py

This is using the new API URL and JSON

Maloja Scrobbling

---

tauon.py

Since Nextcloud airsonic implementation does not support
token-based authentication, this tweak is necessary if you want
to stream from a Nextcloud instance.

Add support for plain password authentication

---

t_modules/t_gstreamer.py
t_modules/t_jellyfin.py
tauon.py

I filled in the functions by using the comments provided. Please review closely as I did not thoroughly test it. There are a couple problems:
- Seeking doesn't work very well
- I had to modify the cover art code as I needed to set an auth header to get the album art. I copied what airsonic currently does. Feel free to change that to whatever works
closes #430

Add support for jellyfin music libraries

---

t_modules/t_spot.py

My proposed fix concerning [this issue](https://github.com/Taiko2k/TauonMusicBox/issues/470)
Tested on Tauon 6.5.3 and is working great

Fix missing tracks in spotify

---

tauon.py

Just a small typo editior -> editor

Spelling typo

---

t_modules/t_main.py

Note sure if this is the correct or most elegant way to do this...but now it shows multiple genres again.

multiple genres for id3

---

.gitignore
extra/repo-install.sh
extra/repo-uninstall.sh

[Previous one](https://github.com/Taiko2k/TauonMusicBox/pull/661) got a bit messy!
This should solve all of the problems with these scripts now.

Fix repo install/uninstall

---

t_modules/t_main.py

This still has a bit work, I've tried several things,
yet managed to fix stops between symbols.
And since isalpha(), isnumeric() and.. wasn't really promising,
I've included them manually, for now

Tiny fix for Ctrl + <>

---

t_modules/t_tagscan.py

Lowercase string before stripping decibel unit

---

t_modules/t_main.py

Get album art from OGA same way as OGG

---

tauon.py

I found it while looking at the version information of this program! It is now 2023.

Change copyright year

---

t_modules/t_main.py

Instead of using tuples, which is difficult to use once there are many values, use a class instead.
Use `__slots__` for speed and memory savings.

Use class instead of tuple for menu items

---

t_modules/t_main.py

There are various context menus that cannot be used on network tracks.
Instead of notifying the user only after clicking such menu items, disable those items so the UI is more user friendly.

Disable network context menus

---

README.md

It has been added to GURU (Gentoo user repository)

add GURU to unofficial packages

---

t_modules/t_jellyfin.py

This pull request enhances the Jellyfin Collection import by updating the GET
request, increasing the import speed, and further populating TrackClass
attributes.
The goal is to decrease the time and system resources for importing /
regenerating a Jellyfin Collection, and more fully populate track information.
The Jellyfin source code indicates the "/Users/{userId}/Items" format for
the Items endpoint is obsolete. Currently it is "Kept for backwards 
compatibility".
https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/ItemsController.cs#L625
To avoid issues in the future if or when it is removed, I've updated the 
request to be consistent with the /Items endpoint format used in the Jellyfin 
API documentation.
https://api.jellyfin.org/#tag/Items
The "filter": "music" …

enhance import

---

t_modules/t_main.py

Fixes #1248 
Decoding was not applying in every case, which it should now.

Fix non-decoded XSPF imports

---

t_modules/t_lyrics.py

* Fix hanging requests
* Type the module
* Convert spaces to tabs
* Add docstrings
* Reduce hadouken
* Use HTTPStatus instead of hardcoded HTTP codes
* Unify quotes
EDIT: Can VSC stop committing to master when I explicitly create a branch??
How is the default behavior a master commit?? This is the third time it happened recently :/

Lyrics module typing, fixes and linting

---

t_modules/t_search.py

* Fix hanging requests
* Type the module
* Convert spaces to tabs
* Add docstrings
* Reduce hadouken
* Unify quotes
* Add logging module and log exceptions

Search module typing, fixes and linting

---

t_modules/t_extra.py

* Type the module
* Convert spaces to tabs
* Add docstrings
* Unify quotes

Extra module typing, fixes and linting

---

t_modules/t_launch.py

Small one, fully type the module

t_launch: Add typing and convert to tabs

---

t_modules/t_main.py
t_modules/t_themeload.py

Needed for #1277
Among other things, this rewrites `get_colour_from_line()` as it was returning both list of strings or ints, depending on the code path.

Themeload module typing, fixes and linting, star import removal

---

t_modules/t_extra.py

It was not precise enough with untyped dicts and I also missed one function type.

Extra module - Fix typing

---

t_modules/t_draw.py

Needed for #1277
Couldn't easily figure out how to do `native_bmp_to_sdl` as it is a Windows function.

Draw module typing, fixes and linting, star import removal

---

tauon.py

Tauon.py: Remove star imports, spaces to tabs, quote unify, docstring

---

src/phazor/phazor.c
t_modules/t_main.py
t_modules/t_phazor.py

Redid #1276 with new changes on top.

Phazor: Typing, fixes, logging and linting

---

t_modules/t_main.py

Also removes some extra whitespace.
Separated from the other PR.

Main: Explicitly catch Exception in every except

---

t_modules/t_webserve.py

This one is incomplete, as the module is fairly complex to me.

Webserve: Partially type, cleanup unused imports, use logging

---

t_modules/t_dbus.py

Tried to make the commits atomic to make it a nicer review.
Setting the Gdk version crashes in this branch as it tried to import 3.0 earlier instead of 4.0, but it works in my working branch with the rest of my changes, so probably merge it only after merging the rest.

Dbus: Typing, fixes, logging and linting

---

update_translations.py

update_translations: Check all commands for errors

---

pyproject.toml

Fix building from pyproject.toml

---

CHANGELOG.md
src/tauon/__main__.py
src/tauon/t_modules/t_bootstrap.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_webserve.py

Tear out last few gui.console.print()s, fix #576, fix trying to open encode directory when it does not exist...

Typing additions, tear out last remaining gui.console.prints, fix whitespace

---

run.sh
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py

Fixes #1333
Fixes issues introduced in #1330, sans passing args to tauon executable which is not necessary at the moment.
Adds a bit more typing.

Fix add to queue crash and run.sh

---

src/tauon/t_modules/t_main.py

Tiny nitpick. Follows the proposal [here](https://github.com/Taiko2k/Tauon/pull/1247#issuecomment-2414441684), I forgot this one bit.

Localizables : Changed "Album Chart" to use .format 

---

src/tauon/t_modules/t_main.py

Fix incorrectly encoded XSPF tags

---

src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_main.py

Mostly typing fixes, wanted to fix up some annoying errors when the file/folder that Tauon is trying to load is deleted, but got stuck on typing again instead

Add more typing, fix .warn deprecation, nicer logging

---

.github/FUNDING.yml

Bumps the template to current upstream standard

Update FUNDING template

---

src/tauon/__main__.py

Improves #1034 so that Tauon at least tries to load in Wayland again as a fallback

Fallback to Wayland if we fail to load in Xwayland

---

src/tauon/t_modules/t_main.py

Add forgotten brackets to prevent a crash.

Fix infobox crash

---

extra/com.github.taiko2k.tauonmb.sh

I believe this is the correct path now
EDIT: Yup!

Fix up Flatpak shell script path

---

src/tauon/t_modules/t_main.py

Fixes a crash reproducible by doing `tauon song.ogg`

Fix playlist crash when opening file

---

src/tauon/t_modules/t_main.py

Fixes crashing when generating incomplete albums

Fix parameter names in gen_ functions

---

src/tauon/t_modules/guitar_chords.py

Makes it usable as a module.
Fixed up the API URL for v3, but unsure if it will work as is, although the URL at least actually works now.
I don't like the amount of passed parameters, we should probably bundle up the positionings and such, but it should do for now.
https://www.guitarparty.com/api/v3/core/?format=json
the v3 api does have a bunch of endpoints and we only seem to use the songs one - 
```json
{
"collection_relations": "https://www.guitarparty.com/api/v3/core/collection_relations/?format=json",
"authors": "https://www.guitarparty.com/api/v3/core/authors/?format=json",
"songs": "https://www.guitarparty.com/api/v3/core/songs/?format=json",
"songbooks": "https://www.guitarparty.com/api/v3/core/songbooks/?format=json",
"chords": …
```

Fix up GuitarChords

---

src/tauon/t_modules/t_webserve.py

webserve: Add missing typing for Strings

---

src/tauon/t_modules/t_main.py

Fix GetSDLInput

---

src/tauon/t_modules/t_bootstrap.py

Boostrap: Fix SDL typing

---

src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_spot.py

#1457 followup, I missed that Spotify uses it too and `self` was missing in main.

Additional QuickThumbnail hotfix

---

src/tauon/t_modules/t_main.py

Fix setting custom encoder path

---

pyproject.toml
src/tauon/t_modules/t_bootstrap.py
src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_prefs.py
src/tauon/t_modules/t_spot.py
src/tauon/t_modules/t_themeload.py
src/tauon/theme/Ash.ttheme

* Cosmetic changes to reduce diff with #1388
* Add new dataclasses from #1388 - they are left unused, this is to lay groundwork for future sync-up PRs
* Add new Ruff linting rules
The only removal here is unused `flatpak_mode` in Prefs.

Add new classes from #1388 and some small cleanups too

---

src/tauon/t_modules/t_main.py

Partial GallClass refactor and TDraw fixup

---

src/tauon/t_modules/t_main.py

These conversions were missed way earlier

Fix purge_track() and test_progress() after TauonPlaylist migration

---

src/tauon/t_modules/t_lyrics.py

This could do an infinite hang

Fix missing LRCLIB timeout

---

src/tauon/t_modules/t_main.py

Fixes #1442
We need to set TLS context env vars BEFORE we import modules that use it.

Fix Last.fm TLS errors in pyinstaller builds

---

src/tauon/t_modules/t_main.py

Originally meant to be along https://github.com/Taiko2k/Tauon/pull/1350,
~~I'll rebase when that'd be ready.~~ It works independed anyway, proceed to do it sooner.

Added timesync for Discord RPC

---

.github/release_body.md
.github/workflows/build_and_release.yaml

Implement building pre-release Flatpaks using https://github.com/flatpak/flatpak-github-actions
Also happens to fix the newest CI failure with latest deps.
Has some cosmetic CI improvements.

Flatpak CI

---

.github/workflows/build_and_release.yaml
extra/msyspac.txt
extra/requirements_linux.txt
extra/requirements_macos.txt
extra/requirements_windows.txt
linux.spec
mac.spec
requirements.txt
windows.spec

Workaround a pyinstaller bug by fixing pygobject to older version

---

src/tauon/t_modules/t_main.py

I had this refactored mostly but without listening my attempt would be waste; so just another small tweak which would be safe.

More time tweaks for RPC

---

src/tauon/t_modules/t_main.py

Fixes #1493, completely this time

Fix and simplify Windows imports

---

src/tauon/t_modules/t_main.py

Replaced it with sys.platform+msys checks.
For real fixes #1493, tested on a VM this time…

Fix Windows import regression and remove `windows_native`

---

src/tauon/t_modules/t_main.py

Broken after SDL3 migration, fixes issue noted in https://github.com/Taiko2k/Tauon/issues/1437

Fix dragging scrollbars

---

src/tauon/t_modules/t_main.py

Fixes #1491, but I am unsure if I am putting things in the correct place.

Fix synced lyrics panel drawing

---

src/tauon/t_modules/t_main.py

Fix loading GLib on macOS

---

src/tauon/t_modules/t_jellyfin.py
src/tauon/t_modules/t_webserve.py

Fix Jellyfin and webserver playlists

---

.github/release_body.md
.github/workflows/build_and_release.yaml
mac.spec
src/tauon/__main__.py

Also moves `debug` check to user-data instead of installation directory.

CI: Enable Windows Inno setup again, add x64 macOS

---

.github/workflows/build_and_release.yaml

The CI broke again, seems like the macOS runners really hate me.

CI: Stop upgrading pip on macOS runners, fixes building

---

src/tauon/t_modules/t_main.py

Tauon doesn't have it, PlayerCtl does.

Fix sm unload

---

src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py

Allows to type up the save states instead of ordering on a dictionary with items in a specific order.

Turn ArtistList save state into a Class

---

src/tauon/t_modules/t_main.py

Moved over some more vars to Bag proper.

Fix variables that were supposed to be in Bag, fix up typing and docs

---

src/tauon/t_modules/t_spot.py

Should fix an issue mentioned in #1199

Fix spotify redirect URI by using explicit IPv4 instead of localhost

---

src/tauon/t_modules/t_main.py

Continued move of variables under classes, cleanup of no longer used vars and fixup of reload_state which is now under prefs proper.

Move more variables under classes, fix reload_state

---

src/tauon/t_modules/t_main.py

Add release_name to ListenBrainz data (album name)

---

.github/workflows/build_and_release.yaml

Fixes an issue mentioned in #1315

CI: Hack macOS images to retry hdiutil on failure

---

src/tauon/t_modules/t_main.py

This potentially fixes issues with CTRL+X parts, as None could've theoretically have been passed.
Purely cosmetic otherwise.

Shorten str != "" checks

---

src/tauon/t_modules/t_main.py

Looks like some servers do not send `isDir` (or have a different format somehow).
Partial fix for #1112

Fix Subsonic isDir check

---

src/tauon/__main__.py
src/tauon/t_modules/t_main.py

Detect NixOS installation directory

---

locale/cs/LC_MESSAGES/tauon.po
locale/de/LC_MESSAGES/tauon.po
locale/es/LC_MESSAGES/tauon.po
locale/et/LC_MESSAGES/tauon.po
locale/fi/LC_MESSAGES/tauon.po
locale/fr_FR/LC_MESSAGES/tauon.po
locale/hu/LC_MESSAGES/tauon.po
locale/ia/LC_MESSAGES/tauon.po
locale/id/LC_MESSAGES/tauon.po
locale/it/LC_MESSAGES/tauon.po
locale/ja_JP/LC_MESSAGES/tauon.po
locale/messages.pot
locale/nb_NO/LC_MESSAGES/tauon.po
locale/nl/LC_MESSAGES/tauon.po
locale/pl/LC_MESSAGES/tauon.po
locale/pt/LC_MESSAGES/tauon.po
locale/pt_BR/LC_MESSAGES/tauon.po
locale/pt_PT/LC_MESSAGES/tauon.po
locale/ru/LC_MESSAGES/tauon.po
locale/sv/LC_MESSAGES/tauon.po
locale/tr/LC_MESSAGES/tauon.po
locale/uk/LC_MESSAGES/tauon.po
locale/zh_CN/LC_MESSAGES/tauon.po

Was not updated for the new features such as transparent accent.

Updated messages.pot, along with .po's

---

src/tauon/t_modules/t_main.py

Possibly last bit of work to be able to get #1388 in.
The extra ctypes definition is needed as after #1388, it ceases to be bound without it - probably due to the way we nest imports to launch the full Tauon window.

Consolidate imports

---

extra/setup.iss
windows.spec

Looks like paths were changed on us

CI: Fix Windows builds

---

src/tauon/t_modules/t_main.py

Fix Show Lyrics crash and improve LRC detection

---

src/tauon/t_modules/t_main.py

Fixes #1658
probably there's a better syntax for this but i wanted to make sure i wasn't using a pointer 
---
EDIT(Martin): Fixed up the syntax to tag the relevant issue, title and used deepcopy.

Fix Left align title style vanishing text

---

src/tauon/t_modules/t_main.py

Move Chrome import to the top and fix shadowing some Python builtins like `id` or `type`, there's still a bunch left to fix.
Throw out a couple now-unneeded migration lines.

Move Chrome import to the top, fix shadow imports, cleanup

---

src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_main.py

Also comments out unused function bass_player_thread()

Fill more typing definitions

---

src/tauon/t_modules/t_draw.py

Adds typing and also fixes some incorrect assumptions to make the typing correct and much less confusing.

Type up TDraw

---

src/tauon/t_modules/t_main.py

partially fixes #1633. I'm also planning to update the remove duplicates function to fix past imports

Fix playlists with relative filepaths importing multiple copies of the same track

---

src/tauon/t_modules/t_main.py

Fixes crash when adding a station
Fixes #1711

Fix add-station crash

---

src/tauon/t_modules/t_main.py

add sorting for internal track id and remove case sensitivity for filepath/filename sorting

fix some sorting in columns mode

---

CHANGELOG.md
src/tauon/t_modules/t_main.py

Fix accidental lyrics clicking in synced mode

---

CHANGELOG.md
src/tauon/t_modules/t_jellyfin.py

Fix Jellyfin import

---

src/tauon/t_modules/t_main.py

Reduce the amount of things that Ruff complains about - down by 43 to 3182, still a long way to go.

Linting fixes and typing

---

CHANGELOG.md
src/tauon/t_modules/t_main.py

Fixes #1752
- default playlist folder box now populates when entering
- playlist export box now interprets text input
- auto import is checked by default on imported playlists
- playlist export type and auto import are now saved correctly
- pl_gen updated

fix a couple playlist file related bugs

---

src/tauon/t_modules/t_main.py

Gets rid of the IndexError logspam

Fix migration checks

---

src/tauon/t_modules/t_main.py

It does not seem to be needed anymore

Remove ctypes load hack

---

src/tauon/t_modules/t_main.py

We were loading the wrong file on Windows.

Fix loading libgme

---

.github/workflows/build_and_release.yaml
.github/workflows/build_extras.yaml

They previously had to be built manually on a dev machine.

CI: Build librespot.exe, TaskbarLib.tlb and TauonSMTC.dll

---

src/tauon/t_modules/t_dbus.py

Fixes #1756
Code Generated Via Gemini Agent Mode

Send "Seeked" signal on track repeat

---

src/tauon/t_modules/t_main.py

Fix synced lyric timestamp identification (Fixes #1776)

---

CHANGELOG.md
src/tauon/t_modules/t_main.py

enable spring-loaded clicking

---

src/tauon/t_modules/t_main.py

fix offset clickable area with synced lyrics display

---

pyproject.toml
src/tauon/__main__.py
src/tauon/t_modules/t_chrome.py
src/tauon/t_modules/t_dbus.py
src/tauon/t_modules/t_enums.py
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_lyrics.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_phazor.py
src/tauon/t_modules/t_prefs.py
src/tauon/t_modules/t_spot.py
src/tauon/t_modules/t_stream.py
src/tauon/t_modules/t_tagscan.py
src/tauon/t_modules/t_themeload.py
src/tauon/t_modules/t_tidal.py
src/tauon/t_modules/t_webserve.py
update_translations.py

Please merge as `rebase` or `merge commit`, not `squash`

Document structures by converting them to enums + linter/typing

---

src/tauon/t_modules/t_main.py

Better bounds for scrolling in synced view

---

src/tauon/t_modules/t_main.py

do u want me to do these all in one branch or in a new branch for each bug?

the first post-merge bug has been found

---

src/tauon/t_modules/t_lyrics.py

fixes https://github.com/Taiko2k/Tauon/issues/1763
removes stuff like
"3 Contributors"
"[Song Name] Lyrics"
"Embed" buttons
"See [Artist] Live"
Ticket advertisements
Related content suggestions

fix genius lyrics scrape picking up artifacts like "3 Contributors"

---

src/tauon/t_modules/t_extra.py

add & and ft. to artist feat strip

---

src/tauon/t_modules/t_main.py

in the synced lyrics editor while playing

fix tauon crash when alt deleting the last line

---

CHANGELOG.md
src/tauon/t_modules/t_jellyfin.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_prefs.py

Bump Jellyfin timeout to 300s and make it configurable
