t_modules/t_gstreamer.py
tauon.py

This PR adds the ability to configure the GStreamer output pipeline
It adds a new option to the `[audio]` section of the configuration file, `gst-output`, which allows the user to tweak their audio output pipeline. For example, `rgvolume pre-amp=-2 fallback-gain=-6 ! jackaudiosink client-name=tauon` would apply replaygain in album mode with custom pre-amp and fallback gain and then output audio via JACK.
In addition to the more outward change, this also drastically reduces the GStreamer polling rate which makes volume control seem more responsive.

GStreamer backend improvements

---

snapcraft.yaml

add the symlinks during build stage on python-deps part in order to get them in the snap (not only prime folder)
ref https://forum.snapcraft.io/t/how-to-use-override-stage/7798/2 & #207

Fix pysdl2 patch

---

locale/fr_FR/LC_MESSAGES/tauon.po

- fixed typo on settings tab ("ecnoder" -> "encoder")
- fixed typo at line 86 ("rennomage" -> "renommage")
- Singular -> plural on line 210 to match source text (Aucune parole trouvée pour cette piste" -> "Aucune paroles trouvées pour cette piste")

Edit french translation

---

tauon.py

With apologies to the maintainer - should resolve #510?
> I have some tracks in my library with differing track Artists and Album Artists. This doesn't seem to be scrobbled (on last.fm, the track is linked to an album under the Artist's name, but not the Album Artist's name).
To describe this in more detail: 
This track is off of the album "works.thE", with the album artist being "Diverse System". When you click "Go to album" on the scrobble, it takes you here:
The scrobble is missing the "Album Artist" property. This fixes that. I think. (It works on my system, at least...)

Add `album_artist` to scrobble

---

extra/repo-install.sh
extra/repo-uninstall.sh

I did this for the lazy ppl (myself included) who don't want to use flatpaks + like to build the apps they can't find on their distro.
If you clone the repo with `--depth=1` and just run the script, ta-da: Tauon is deployed on the desktop and you just clean+fetch+pull git to update, then re-run `repo-install.sh` again.
Anyway, sorry if this is more trouble than it's worth... Just though someone else might wanna skip some hours of torture. I mean enjoyable torture; learning is fun!

Add install scripts to deploy the repo itself as an desktop app

---

.gitignore
extra/repo-install.sh
extra/repo-uninstall.sh

So it leaves the tracked files alone.
I also took the liberty to add the `*.tmp.*` line in `.gitignore`. Is that fine? I'll change it back if is not.
I added it in just in case there is no change in the original `extra/tauonmb.*` files and the user wants to update their repo without worrying about them. Either way, if the user would just run the script again, the `*.tmp.*` files will be overwritten and any problem originated from keeping the temporary files between updates will be gone.
Original idea taken from #667 comment section.

Change `extra/repo-install.sh` to clone `extra/tauonmb.*` intead of changing them directly

---

extra/repo-install.sh
extra/repo-uninstall.sh
extra/tauonmb.desktop

I think this is final :)
Now the parsing only happens to `tauonmb.tmp.desktop`, making the necessary "shortcuts".
Also, small fix on the original `tauonmb.desktop` file... even though I realize now that the stop request isn't even used; line 24.

Removes the need for `tauonmb.tmp.sh`

---

tauon.py

Dev mode ignores single instancing. However, whether we launch in dev mode is based on the presence of a .gitignore file *in the current path*. This check was too simplistic and would result in accidental dev invocations.
For example, when the user has a global .gitignore file in their $HOME directory. Launchers, e.g. rofi, will use $HOME as their current directory. The simplistic check will assume the global .gitignore file to be this project's file instead.

Fix accidental dev invocation.

---

t_modules/t_phazor.py

If Tauon is closed while it is playing a song (e.g. playing from Jellyfin), then the following error message is shown:
Fixing this by obtaining the proper cross-platform tmp directory.

Fix PermissionError upon exit on Windows

---

src/phazor/phazor.c
t_modules/t_phazor.py

There are 2 commits.
The first one fixes an issue with phazor where it uninit the ma_context right away.
For WASAPI backend, `ma_context_uninit__wasapi` will quit the command thread.
Without the command thread, WASAPI can't function properly when a device is removed and added again.
In this situation, the only way to get Tauon to function again is to close it completely and re-open.
The second diff pauses the music when audio device gets removed.

Pause music when output device is removed

---

.gitignore
t_modules/t_main.py
tauon.py

This diff adds code to avoid saving state by default while in dev mode. It can still be enabled via the MENU if needed.
The benefit of this is that when someone is developing or debugging, perhaps repeatedly playing songs, doing that won't artificially change things.

Dev Mode: Default to not saving state

---

t_modules/t_extra.py
t_modules/t_main.py
t_modules/t_phazor.py

#932 fixed the location of the audio-cache dir on Windows, but I found that "/tmp/TauonMusicBox" path is still being used at several places.
Closing the app doesn't properly clean the cache dir after #932.
Fixing this by changing all instances of "/tmp/TauonMusicBox" to be cross-platform compatible.

Fix /tmp/TauonMusicBox being used on Windows

---

t_modules/t_spot.py

When I was trying to import all of my Spotify playlists, I ran into this error:
```
Exception in thread Thread-13 (import_all_playlists):
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
self.run()
File "/usr/lib/python3.11/threading.py", line 975, in run
self._target(*self._args, **self._kwargs)
File "/app/bin/t_modules/t_spot.py", line 294, in import_all_playlists
self.playlist(item[1], silent=True)
File "/app/bin/t_modules/t_spot.py", line 773, in playlist
nt = self.load_track(item.track, include_album_url=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/bin/t_modules/t_spot.py", line 961, in load_track
if "spotify" in track.artists[0].external_urls:
^^^^^^^^^^^^^
AttributeError: 'FullPlaylistEpisode' object …
```

Check type of track before trying to load.

---

CMakeLists.txt
setup.py
t_modules/t_main.py
t_modules/t_phazor.py
tauon.py

Closes: #828
- added a CMakeLists.txt to build phrazor component. 
- added a setup.py to build the t_module python module to be able to be installed with the standard approaches of different Linux distros.
- modified install_directory when the program is installed under /usr so it seeks assets in the standard /usr/share directory

Improve support for more easy packaging from Linux distros

---

src/phazor/phazor.c

Playing single channel opus files results in incorrect audio output.
Playing a wav file after playing a single channel opus file also produces incorrect output, but after playing a two channel file (any) then playing the wav again the audio is fine. 
These changes should fix the two issues.

Fixes two issues for reading single channel files

---

t_modules/t_main.py

It now uses both `release_group_id` and `release_id`, which makes it significantly more reliable.

Tweaked Discord album art implementation to make it more reliable. Closes #1136.

---

extra/win-requirements.txt
requirements.txt
t_modules/t_lyrics.py
t_modules/t_main.py

isounidecode don't have any new commits (nor releases) since 7 years ago. Also, seems that distros don't tend to package it (at least Gentoo, Debian and Fedora). 
Unidecode seems to be API compatible and work out of the box and is more active.

replace isounidecode with unidecode

---

t_modules/t_jellyfin.py

This pull request is for adding Genres to a Jellyfin playlist/collection.
Genres are not included by default in the GET response of the Items endpoint. According to the Jellyfin API documentation, the "fields" parameter allows you to "Specify additional fields of information to return in the output." One of those fields is Genres.
https://api.jellyfin.org/#tag/Items/operation/GetItems
I changed the Jellfyin module to add a "fields" parameter to include the Genres field, and naturally added a variable to capture the Genre(s) in the Jellyfin import loop.
I've tested the changes and everything seems to work. Genres appear in the columns view of the Jellyfin Collection and I'm able to filter and create playlists based on the Genre.

add jellyfin genres

---

CONTRIBUTING.md
t_modules/t_jellyfin.py

In the Jellyfin json response there can be more than one "MediaStreams" dictionary. In my audio files the first (or only) one is usually audio, but I've discovered in some cases the first stream is cover art.
This pull request ensures that the TrackClass attributes populated from the MediaStreams dictionary is from the audio media stream rather than some other. I was also sure to include a default in the event one of the attributes were missing.
I've also added a fallback empty string for the nt.date and nt.container attributes in the event they are missing, as well as changing the enableImages query parameter from 'false' to False (it works either way, but the latter seems more "correct"). All the other attributes already have a fallback, or do not need one because it would otherwise not …

Specify Audio MediaStreams

---

t_modules/t_main.py

Also made separator into `|` instead of `-`, which I think improves visual separation.
I made this change because long artist names would often completely obscure the song name in Discord, while I prefer if the song name itself is visible over the artist. While updating my tags to have shorter artist names and removing featured artists could work, I think this is a preferable solution.
Some examples follow. I highlighted the song title with a red box.
---
---

Flipped `artist` and `track name` in Discord Rich Presence

---

pyproject.toml
t_modules/t_main.py
t_modules/t_phazor.py
t_modules/t_spot.py
t_modules/t_webserve.py

Follow up to #1251.
There's a couple things to go through:
* Single vs Double quotes - it would be nice to consistently use one formatting
The codebase uses quotes pretty much randomly:
I've added a linter rule that ensures single quotes everywhere (docstrings remain double quoted, as per PEP recommendations).  
If double quotes are desired instead, let me know and I'll swap it.
* Spaces vs tabs - It would be nice to use tab indents, as that will allow everyone to view the code at the indentation width they prefer  
Using tabs goes directly against PEP8. In my opinion, this PEP8 recommendation is nonsense today, as Python handles indentation amazingly for both, and tabs allow people their own indent preference.  
Everyone uses something else - I prefer 2-width, htop uses 3-width, TMB uses …

Add basic linter rules and partially type Phazor, Spotify and Webserve

---

t_modules/t_jellyfin.py
t_modules/t_main.py

Review by the second commit to ignore whitespace - https://github.com/Taiko2k/Tauon/pull/1268/commits/afb0a19523d018acd1ff5df0d51a88e56d82b4ad
This also touches on t_main to be able to properly type Jellyfin.
Notably, it adds a new TauonPlaylist dataclass.
Removed a useless url = line that even used a dead compat requests Python 2 function.
Commented out an unused headers block - maybe that one should be used instead?
Should fix any remaining #1222 issues due to fixing indefinite timeouts in `requests`.

Jellyfin module typing, fixes and linting

---

src/tauon/t_modules/t_db_migrate.py
src/tauon/t_modules/t_main.py

```Python
user_directory   = Path(GLib.get_user_data_dir())  / "TauonMusicBox"
config_directory = Path(GLib.get_user_data_dir())  / "TauonMusicBox"
```
This was wrong and should have been string, only ran into it on the regular OS install and not the venv build.
user_directory is now string again for now, and config_directory was converted proper.

main, db_migrate: Hotfix user_directory and convert config_directory to Path

---

src/tauon/t_modules/t_main.py

This is already done in `tauon.py`, so fixing the bug there was not enough... just remove it from main.
It looks like the original PR adding it made sense, but it was added to Holder later and de-dupe was missed.

Main: Remove duplicated code causing issues

---

src/tauon/t_modules/t_main.py

The previous implementation didn't check type and threw an error on every single song in the list.

Main: Fix tryint() throwing errors

---

CHANGELOG.md
run.sh
src/tauon/__main__.py
src/tauon/t_modules/t_chrome.py
src/tauon/t_modules/t_jellyfin.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_phazor.py
src/tauon/t_modules/t_spot.py
src/tauon/t_modules/t_themeload.py
src/tauon/t_modules/t_webserve.py

Fixes up one issue out of two in #1291
Had to move the Menu class so the diff is a bit wonky when viewed together.
Fixes a bunch of missed g() renames.
Enables additional (??? docs make it look like they're default) warnings like:
```python
/home/user/Projects/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py:44663: 
ResourceWarning: unclosed file 
<_io.TextIOWrapper name='/home/user/Projects/Tauon/.venv/lib/python3.12/site-packages/tauon/theme/Turbo.ttheme' mode='r' encoding='utf-8'>
load_theme(colours, theme_item[0])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
Fixed all revealed warnings by the above, this involves not closing file handles in various places, themes and DB accesses included.  
May fix memory leaks that some people …

Chromecast fixups, run.sh dirty venv mode, typing, enable warnings module and fix closing file handles

---

.github/workflows/build_Linux.yaml
.github/workflows/build_Windows_MINGW64.yaml
.github/workflows/build_macOS.yaml
CHANGELOG.md
extra/requirements_linux.txt
extra/requirements_macos.txt
extra/requirements_optional.txt
extra/requirements_windows.txt
linux.spec
pyproject.toml
requirements.txt
run.sh
src/tauon/__main__.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_phazor.py
windows.spec

Adds CI file for building Windows releases too and has some fixes for the Windows build.
Ticks a box in #1315
Fixes a leak in Phazor.
Migrates from dead infi.systray to my fork lynxtray.
A little bit of typing.
Adds missing pysdl2-dll dep to reqs.txt.
Fixes jxlpy for macOS builds.
Fix Linux builds, they were unusable due to lack of Gdk, Ayatana appindicators and librsvg. 
Bundle Plasma/GTK comaptibility libs for GTK 3.0 on Linux builds.
Make Tauon exit with a helpful error if it detects a database format newer than it knows.  
i.e. running Tauon that only knows v69 DBs against a Config directory that was created using v70, it will refuse to load and exit.  
This will obviously not work for any release pre-7.9.0, as it won't have the check.

Add Windows CI and fix up Linux and macOS

---

extra/msyspac.txt

Windows CI is broken without this.

Fix Windows CI after python3 -> python rename

---

src/tauon/t_modules/t_main.py

We were throwing away the entire dictionary in this function by setting it as string.
We were also not converting duration to int.
We were also not dealing with artist IDs split by a slash in listenbrainz - maybe this part should be dealt with higher up instead - in the library? Works as is though and I am too lazy to make an upstream report right now.
Fixes #1190 (with a bit of hopium)  
Fixes #1379

Fix ListenBrainz integration

---

.github/workflows/build_macOS.yaml
extra/requirements_macos.txt
mac.spec
requirements.txt

We were suggested to not mix and match Brew and pip to avoid issues like the one in this thread - https://github.com/orgs/pyinstaller/discussions/8974
Remove most of the venv parts and use system Python instead of GitHub one.

Switch macOS CI partially away from venv and more towards brew

---

src/tauon/t_modules/t_main.py

Improvements for the Maloja scrobbling feature.
- Sending JSON data as recommended by the [API documentation](https://github.com/krateng/maloja/blob/master/API.md#api-documentation).
- Now using the `artists` field. The old `artist` field is [still supported](https://github.com/krateng/maloja/blob/c6cf28896ca836407a1943cae5542d2b83d009cf/maloja/apis/native_v1.py#L590), but it is likely deprecated as it is not mentioned in the [documentation](https://github.com/krateng/maloja/blob/master/API.md#submitting-a-scrobble).
- Added `album`, `albumartists`, `length`, and `time` fields.

Improve Maloja scrobbling

---

src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py

Handle passing infinity to `get_display_time()` by logging an error and parsing ??:?? back, this fixes an instant crash should we supply such a file that manages to get mangled by tag_scan() as such.
Also handle the root cause that was causing this - we were not handling a possible infinity libopenmpt can throw if it fails to parse the file length.
Upstream report - https://bugs.openmpt.org/view.php?id=1857
Also fix typing for the function and add some small touchups.
Repro broken .mod file was posted in https://discord.com/channels/687418493209018622/915799586168270878/1328664124254715934

Fix getting length from libopenmpt as infinity, which could crash with Protracker modules

---

linux.spec
src/tauon/t_modules/t_phazor.py

Add phazor-pw to hidden imports to fix PipeWire on the Linux prebuilt.
Use a ternary operator in `phazor.py`

Fix Linux CI phazor-pw

---

src/tauon/__main__.py

We have no good way of logging things on Windows/macOS, so let's add logging to a file to user-data dir.
It does not log the very beginning of the logs as the handler is added dynamically, but it should suffice.

Log to tauon.log too if debug is enabled

---

src/tauon/t_modules/t_main.py

Mostly cosmetic - couple message modes were missed so they were logging as error, this catches them correctly and logs them as debug instead.

Add missing modes for show_message()

---

src/tauon/t_modules/t_jellyfin.py

Jellyfin: Bump import timeout from 10s to 120s

---

src/tauon/t_modules/t_main.py

Take some ideas and fixes from #1388
Move all the code to the bottom, after all the function and class definitions.
Tiny fixes for things I spotted while moving the code, mostly just docstrings/whitespace.
Small fix for GuiVar/Colours where there should have been `self` used.
This makes it very easy to spot some mistakes (which I did not attempt to fix here) like lack of translations on some menu strings.

Define classes and functions in t_main first before running code

---

src/tauon/t_modules/guitar_chords.py
src/tauon/t_modules/t_main.py

Not happy with the added hack for the t_main function but not wanting to do massive reworks either at the moment, so I hacked it in for now, it's a couple lines of code...
Migrated to GuitarChords v3 ***internal*** API, inherently unstable, but works for now, there's no other option other than scraping the 0.5GB of data from GuitarChords and searching against a cached copy.
It looks like the new API has a bit different output and some of the lyrics are off due to indents?

Fix up and re-enable GuitarChords integration

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This will help autotag issues and help users file better quality reports
New bugs automatically get `unconfirmed bug` and new feature requests the newly added `propsal` tag, the idea is to re-tag them as `bug`/`enhancement` later if they are accepted and to be able to differentiate between the two.

Start using Issue Templates

---

src/tauon/t_modules/t_db_migrate.py
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_stream.py

Radio playlists used multinested list of dictionaries, converted it to classes instead.
```python
radio_playlists: list[dict[str, int | str | list[dict[str, str]]]]
radio_playlists: list[RadioPlaylist] 
```
* Exit if we fail to run migrations
* Requires a database bump (now 70)
* Corrects typing for RadioPlaylist variable in db_migrations
* Fixes gensokyoradio.net fallback URL (I thought I did that ages ago??)
* Stop setting scroll == 0 on Stations, it was there in one place in the code, makes no sense to me and seems like a mistake, should be set on Playlist instead?

Start using classes for Radio playlists and stations

---

src/tauon/t_modules/t_db_migrate.py

Fixes migrations if someone had pre-existing non-default radios.

Hotfix radio migrations

---

src/tauon/t_modules/t_main.py

Fixes #1427
We could reduce the code paths by simply changing this on Flatpak side instead, but this works too.

Fix Flatpak localization

---

src/tauon/t_modules/t_main.py

It was used wrong after converting it to a class.

Fix get_track_in_playlist()

---

src/tauon/t_modules/t_main.py

Since they're Path now it fails to concat.

Fix override logging lines

---

.github/workflows/build_Windows_MINGW64.yaml
.github/workflows/build_macOS.yaml
README.md
extra/msyspac.txt
extra/requirements_linux.txt
extra/requirements_macos.txt
extra/requirements_windows.txt
linux.spec
mac.spec
pyproject.toml
requirements.txt
src/tauon/__main__.py
src/tauon/t_modules/t_main.py
windows.spec

Both brew and msys now ship sdl3 and sdl3_image.
Windows seems to need sdl3_ttf too, or at least the launch fails without it on a crc checksum failure when it tries to download it...
the pysdl env var seems to have been renamed - https://pysdl3.readthedocs.io/en/latest/install.html#custom-binaries
EDIT: Actually it looks like pysdl3 will always download all missing libraries without overrides and requires all extra SDL libraries anyways - raised [here](https://github.com/Aermoss/PySDL3/issues/15)
This is great on Linux where we don't have the libraries shipped on 24.04 Ubuntu that we build from, not so much on Windows/macOS.

Small CI and SDL3 fixups

---

src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_prefs.py

Start pushing larger changes from #1388 - converts the Prefs class to a dataclass
This makes it nicer to define by getting rid of the init function and all the `self` references.  
Logic for the couple vars that had it is now handled outside of the class.

Convert Prefs to a dataclass

---

src/tauon/t_modules/t_main.py

Makes sure manual_directory is Path in both cases, fixes an extra path separator and stops translating output

Fix up transcode_single()

---

src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_main.py

This mildly refactors QuickThumbnail and GallClass since I had to pass `ddt` to QuickThumbnail, so I applied the idea of #1388 to pass Tauon around (and temporarily pass `renderer` into `Tauon` until #1388 is in and it passes the full scope)

Fix remaining missed SDL3 conversions

---

src/tauon/t_modules/t_main.py

Calls for the function use `target_track` but the parameter is `track` and `track`/`target_track` is used interchangeably within the function, it does not crash because of implicit globals, but the behavior is probably wrong.

Fix l_panel() variable name

---

src/tauon/t_modules/t_main.py

This worked til now since it ended up relying on an implicit global I suppose.

Fix download_img() parameter

---

src/tauon/t_modules/t_main.py

No clue what this ends up causing, but one of the vars is misnamed as `so` instead of `to`.

Fixup Undo.undo() using wrong var name for scrobbling

---

src/tauon/t_modules/t_main.py

Changes should fix two scenarios:
- Issue with first track which was on selection, when we wanted to go down, there was one extra selection.
- Issue which has caused by the last track selection in the upward direction, which was exceeding the range of the list, resulting the selection was getting stuck at the end of the list.

Fix on shift selection

---

.github/release_body.md
.github/workflows/build_and_release.yaml
extra/setup.iss

https://jrsoftware.org/ishelp/index.php
Fixes #1445

Implement Inno Setup in CI

---

.github/workflows/ruff.yaml

Adds a Ruff run to the CI against the ruleset defined in pyproject.toml.
Disabled on `master` for now as this needs #1388 to be any useful, the ruleset needs changes too, but the job otherwise works just fine.  
If this were enabled as-is, we'd make all CI jobs have an ugly red checkmark.

Add Ruff to CI steps, disabled for now

---

src/tauon/t_modules/t_main.py

Seems like a missed conversion, the extra "\n" was problematic.

Fix crash on UniDecodeError exception

---

.github/release_body.md
.github/workflows/build_and_release.yaml
src/tauon/t_modules/t_draw.py

Fixes #1464, this is some very weird sdl3/pysdl3/pyinstaller bug with named parameters, where it just eats them if they're named in certain conditions (Our GitHub CI seems to be a requirement for build at least?)

Fix CI builds not being able to render images

---

src/tauon/t_modules/t_draw.py

Did a whoopsie due to https://github.com/Aermoss/PySDL3/issues/16

Use c_size_t in t_draw.py, upstream has mismatched typing

---

src/tauon/__main__.py
windows.spec

Currently we ship them in the root of the program as per PySDL2, but in PySDL3 they're expected in ./sdl3/bin by default.
We set the appropriate env vars to ensure PySDL3 does not try to autodownload and override the lib dir to `.` pwd.
Related issue - https://github.com/Taiko2k/Tauon/issues/1437
Windows only, macOS and Linux is TODO.

Ship our own SDL3 binaries in Windows CI releases

---

.github/workflows/build_and_release.yaml
mac.spec
src/tauon/__main__.py

Fixes up using SDL3 dylib and only uses system libs for SDL3 outside of pyinstaller

Ship our own SDL3 binaries in macOS CI releases

---

README.md

Swap "unofficial packages" for Repology status in the readme

---

src/tauon/t_modules/t_main.py

Instead of calling `phazor_exists()` on every Overlay redraw, cache it once on init and reuse the cache.
Also adds init bits from #1388 for future use.
Fixes #1346

Only check Phazor presence once

---

src/tauon/t_modules/t_main.py

Small sync-up PR with #1388 
* Moves couple imports to the top, allowing them to be properly accessible when the code is later wrapped in a main() function
* Fixes apply_transparency() typo
* Adds two commented out type_enforced import and setup lines for debugging typing

Move more t_main imports to the top

---

src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_phazor.py

Part of #1388, allows defining Cachement and LibreSpot (and FFRun) properly without having to set them as None first.
Removes an implicit `state` global and uses it as `tauon.player4_state` instead.
Follows the convention of defining functions before executed code.

Refactor t_phazor.py to put classes in root of the module

---

src/tauon/__main__.py

Current workaround breaks Flatpak instead of breaking AUR version.

Fix both Flatpak crashing on `SDL_DOC_GENERATOR=1` and AUR on `0`

---

src/tauon/t_modules/t_main.py

Another PR for https://github.com/Taiko2k/Tauon/pull/1350 afterward

Rewriting rpc stuff, again?

---

src/tauon/t_modules/t_main.py

Looks like two Windows things were executing when they shouldn't be - font settings and drag and drop of text - we set `system` to `Windows`, not `windows`, these checks would never pass.
I'm not sure if the logic *actually* shouldn't be executing, but the checks are wrong.
Mildly relevant to #1318

Fix capitalization for Windows checks

---

src/tauon/t_modules/t_main.py

Got this crash on latest git when clicking to enable persistent network cache. 
```
Traceback (most recent call last):
File "/home/mike/Tauon/src/tauon/__main__.py", line 457, in <module>
main()
File "/home/mike/Tauon/src/tauon/__main__.py", line 454, in main
from tauon.t_modules import t_main
File "/home/mike/Tauon/src/tauon/t_modules/t_main.py", line 45825, in <module>
pref_box.render()
File "/home/mike/Tauon/src/tauon/t_modules/t_main.py", line 13271, in render
self.tabs[self.tab_active][1](x + side_width, y + header_width, content_width, content_height)
File "/home/mike/Tauon/src/tauon/t_modules/t_main.py", line 10675, in audio
tauon.cachement.__init__()
TypeError: Cachement.__init__() missing 1 required positional argument: 'tauon'
```
Passing tauon instance to constructor.

Fix crash when enabling persistent network cache

---

extra/com.github.taiko2k.tauonmb.desktop
extra/tauonmb.desktop

Fixes #1047
DEs such as Gnome and KDE allow to configure desktop notifications per-application. To enable that, the following line should be present in the `.desktop` file:
```
X-GNOME-UsesNotifications=true
```
See https://developer.gnome.org/documentation/tutorials/notifications.html#disabling-notifications

Enable fine grained control over desktop notifications

---

src/tauon/t_modules/t_main.py

Accidentally used equivalent of pctl.pctl

Fix wrong pctl reference

---

src/tauon/t_modules/t_main.py

There's two instances (this PR creates the second one) where I had to comment out `scroll=0` and just wanted to confirm before I remove the two commented out lines entirely that it's correct.
It seems to me that the idea was to set scroll for playlists only, but due to the fact both stations and playlists were dictionaries and not class objects it was mistakenly being set here too when it's not needed.

Fix reading radio playlists

---

src/tauon/t_modules/t_main.py

encoder_output is now a Path object and it was still treated as string.

Fix opening encode output directory on Windows

---

linux.spec
src/tauon/__main__.py

Fixes #1539
Prevents mix and matching files from multiple Tauon installations.
Related pyinstaller discussion, as I initially went on a much different path before discovering the actual issue - https://github.com/orgs/pyinstaller/discussions/9103

Fix loading modules from system install when using a local directory

---

src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_tagscan.py

Fixes #1578
Looks like `albumartists` can be defined multiple times too, so account for it instead of throwing everything but the last definition.
It's not ideal, as we save the first album artist only, but current behavior only uses the last one, whereas the first one is seemingly always the actual main album artist, later ones being secondary.
Second commit simplifies the module a bit by means of introducing a base class.

Deal with multiple albumartist tags in FLAC and OPUS files

---

.github/workflows/build_and_release.yaml

It seems the shell has exit on error by default nowadays, so the OG workaround does not apply anymore.

CI: Fixup macOS hdiutil workaround

---

src/tauon/t_modules/t_main.py

Fixes #1587, Picard now ships as a 64-bit app so it's no longer in the 32-bit path.
Out of date Picard installations will no longer work after this, but there should be no blockers for people to update.

Fix launching Picard on Windows by using the new 64-bit path

---

src/tauon/t_modules/guitar_chords.py
src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_prefs.py
src/tauon/t_modules/t_spot.py
src/tauon/t_modules/t_tagscan.py
src/tauon/t_modules/t_themeload.py

Adds `ColourRGBA` class and converts the entire codebase to use it instead of `list[int]`.
Instead of using `colour[2]`, we now do `colour.b` for blue, etc.
There's also a small typing commit tacked on.

Add a class for defining RGBA colours

---

src/tauon/t_modules/t_main.py

`heart_colours` was defined globally but it's accessed from inside of `Tauon` elsewhere, so let's move it there.
Also commented out `power_tag_colours` as it seems unused anywhere.
Also fixes some color typing and missed defining a color somewhere as `0` (which was wrong even when it was a list of ints).
Fixes some missed ColorRGBA conversions too.

Fix colour typing and definitions

---

src/tauon/t_modules/t_main.py

Continuation of typing up the codebase, gets rid of/comments out a couple variables that seem completely unused, or were used in the past but are now commented out except for the init.
Renamed `type` to `name` in one function as `type` is a reserved keyword in Python.

Migrate timers, more typing additions

---

src/tauon/t_modules/t_main.py

Fixes some image leaks when first loading an album.

Make sure source_image is closed to prevent resource leaks

---

src/tauon/t_modules/t_main.py

Covert art wasn't loaded after ColourRGBA conversion in some cases.

Fix loading cover art

---

src/tauon/t_modules/t_main.py

Fixes #1615
Remove icon first before attempting to open it as writable as we may otherwise open a read-only file.

Fix enabling monochrome tray icons on NixOS

---

src/tauon/t_modules/t_main.py

Fixes #1112
Fixes #1225
Fix crashing on failed login with some Subsonic implementations and actually show the error message to the user
Fix failed login with some Subsonic implementations due to them sending raw control characters in JSON replies
Raise an exception if a Subsonic cover is a failed response and not a raw image - reported in #1112 - combination of bad lms implementation of error messages and us sending over `id` instead of `coverArt` values
Fix sending `id` instead of `coverArt`, breaking cover arts on some implementations.
My only worry here is if Airsonic still works with cover art as I have no instance to test with, LMS(now fixed) and Navidrome(still works) work fine. It presumably fixes Nextcloud Music too.

Subsonic fixes

---

src/tauon/t_modules/t_main.py

Return empty array instead
Should fix this bug:
```python
Traceback (most recent call last):
File "/usr/bin/tauonmb", line 8, in <module>
sys.exit(main())
~~~~^^
File "/usr/lib/python3.13/site-packages/tauon/__main__.py", line 456, in main
from tauon.t_modules import t_main
File "/usr/lib/python3.13/site-packages/tauon/t_modules/t_main.py", line 44855, in <module>
tauon.bottom_bar1.render()
~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/usr/lib/python3.13/site-packages/tauon/t_modules/t_main.py", line 27499, in render
pctl.show_current()
~~~~~~~~~~~~~~~~~^^
File "/usr/lib/python3.13/site-packages/tauon/t_modules/t_main.py", line 2375, in show_current
ap = self.tauon.get_album_info(i)[1][0]
~~~~~~~~~~~~~~~~~~~~~~~~~^^^
File "/usr/lib/python3.13/site-packages/tauon/t_modules/t_main.py", line 17766, in …
```

Fix a crash stemming from reload_albums() returning None

---

src/tauon/t_modules/t_db_migrate.py
src/tauon/t_modules/t_extra.py
src/tauon/t_modules/t_main.py

Refactor StarStore to use class object instead of a list.
Removes `flags` parameter as it was only used for loving a track, now there's a boolean.
Removes an unused `album` variable.
Fixes breaking *really old* migrations, as star_store wasn't being loaded before migration was being processed.
Fixes a bug where the list had an incorrect amount of values, breaking loving a track:
```python
2025-05-18 01:57:27 [CRITICAL] [  t_main  ] [1069.17647152688, '', 0] (t_main.py:15846)
Exception in thread Thread-16 (love):
Traceback (most recent call last):
File "/usr/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
self.run()
~~~~~~~~^^
File "/usr/lib/python3.13/threading.py", line 992, in run
self._target(*self._args, **self._kwargs)
~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Use new StarRecord class for StarStore objects

---

src/tauon/__main__.py
src/tauon/t_modules/t_bootstrap.py
src/tauon/t_modules/t_main.py

This is effectively a complete refactor of Tauon's Python side.
This introduces a new dataclass called `Bag` in `t_main.py`, created after `Prefs` (technically it could be merged into `Prefs`, but that is big enough and it's not a Preference but mostly an object holder), which partially absorbs the initial `Holder` from `__main__.py`, and later the `Tauon` class absorbs `Bag` and `Holder`.
Things were rearranged to allow this hierarchy, most classes are now initialized within `Tauon` or `PlayerCtl`, as needed.
This allows us to pass `Holder`, `Bag` and later `Tauon` everywhere, allowing access to all the things that used to be either explicit or implicit globals, all the while allowing type checkers to understand the code and not crash/timeout as is the current case with `master`.
Works …

Refactor initialization, functions and classes

---

.github/workflows/ruff.yaml

This adds a Ruff check that always returns OK in the end, currently has `|| true` as we're dragging some 3.3K issues along, when that is sorted, we can remove it and actually start adhering to the defined rules.
For now this is here so we can check the remaining issues in the CI, one has to open the Open Ruff step.
It's nicely formatted for the GitHub console too.

CI: Run Ruff

---

.github/workflows/build_and_release.yaml

Bump Inno-Setup-Action to 1.2.6
Use whatever drive letter for .ISS that the runner is using, seems to fluctuate at random between C:\ and D:\

CI: Fix Windows runner

---

src/tauon/__main__.py

Aims to workaround the bug in #1625 but PySDL3 has [another bug](https://github.com/Aermoss/PySDL3/issues/36) which prevents importing, so the PR is broken with current versions.

Add a workaround for #1625

---

src/tauon/t_modules/t_main.py

When displaying synced lyrics:
- you can click a line to teleport to it in the song
- you can scroll freely while the song is playing
- the view will snap back to default position after 5 seconds of not scrolling
- if the currently active lyric is not in the view, the view will not snap when active lyric advances
- spacing improved
- scrolling is bounded at the top and bottom of the lyrics
resolves #1653

Synced mode: click to seek to lyric, scrolling while playing

---

src/tauon/t_modules/t_main.py
src/tauon/t_modules/t_stream.py
src/tauon/t_modules/t_webserve.py

We still ship an ancient 5.x version at the moment.
Guts out #1598 to get the non-controversial changes from it.
This stops hardcoding the total filesize (except the initial prompt and fail of getting the size from the headers).
Stops hardcoding the exit to a certain filesize.

Bump Windows ffmpeg to 7.1.1

---

src/tauon/t_modules/t_main.py

We were loading it into nothing after an earlier refactor.

Fix loading queue

---

src/tauon/__main__.py
src/tauon/t_modules/t_main.py

This was removed during migration to SDL3 but it is still useful.
I was not able to figure out why `SDL_VIDEODRIVER` is now ignored but I haven't really tried hard, so for now we just unlink the file and don't attempt to re-launch.

Fix typing and add back X11 fallback removal

---

src/tauon/t_modules/t_draw.py
src/tauon/t_modules/t_spot.py

- Spotify search may return FullTrack which has no "images" attribute.
Added check which reassigns "album" object to the variable in this case.
- SDL3 has removed the functions "SDL_QueryTexture" and "SDL_RenderCopy" 
Not all instances of removed functions fixed in this commit
See the migration guide: https://wiki.libsdl.org/SDL3/README-migration
Fixes issue: #1513

Fix Spotify search and SDL3 crash

---

src/tauon/t_modules/t_main.py

previously in the synced editor you could scroll with the mouse wheel, then use the enter key and the active line would jump upwards. no longer

fix timing scroll shortly after manually scrolling

---

CHANGELOG.md
src/tauon/t_modules/t_jellyfin.py

Fixes #1087
I am not sure if I did this correctly, as Jellyfin only gives one value for normalization gain.
Seems to work, though?
```
2025-09-25 13:17:26 [ DEBUG ] [ t_phazor ] Detected Replay gain (t_phazor.py:603)
2025-09-25 13:17:26 [ DEBUG ] [ t_phazor ] GAIN: -12.78 (t_phazor.py:604)
2025-09-25 13:17:26 [ DEBUG ] [ t_phazor ] PEAK: 1 (t_phazor.py:605)
2025-09-25 13:17:26 [ DEBUG ] [ t_phazor ] FINAL: 0.2296148648112362 (t_phazor.py:606)
```

Use Jellyfin's NormalizationGain as replaygain_track_gain
